server:
  port: 8080
service:
  version: 1.0.0
spring:
  application:
    name: center-demo
  profiles:
    active: local

dubbo:
  application:
    id: 'center-demo'
    name: 'center-demo'
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: false
  scan:
    base-packages: com.example.center
  consumer:
    check: false
